version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: uaa
    volumes:
      - ../data:/var/lib/postgresql/data
      - ./init/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  db-admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080